edo = '344 - NAY.'
edo = edo.replace(' ','')
edo = edo.replace('-','')
edo = edo.strip('.')
for n in range(0,9):
    edo=edo.strip(str(n))
estado = edo    

# edo2 = edo1.strip('.')
# edo3 = edo2.strip('0')
# edo4 = edo3.strip('1')
# edo5 = edo4.strip('2')
# edo6 = edo5.strip('3')
# edo7 = edo6.strip('4')
# edo8 = edo7.strip('5')
# edo9 = edo8.strip('6')
# edo10 = edo9.strip('7')
# edo11 = edo10.strip('8')
# edo12 = edo11.strip('9')
print(estado)

# dist = '1 - Santiago Ioahgfak'
# dist = dist.replace(' ','')
# dist = dist.replace('-','')
# edo3 = edo2.strip('A')
# edo4 = edo3.strip('B')
# edo5 = edo4.strip('C')
# edo6 = edo5.strip('3')
# edo7 = edo6.strip('4')
# edo8 = edo7.strip('5')
# edo9 = edo8.strip('6')
# edo10 = edo9.strip('7')
# edo11 = edo10.strip('8')
# edo12 = edo11.strip('9')
# dist = '1 - Santiago Ioahgfak'
# dist = dist.replace(' ','')
# dist = dist.replace('-','1234567')
# dist = dist.srtrip('1234567')
# dist = dist.rstrip('A')
# dist = dist.strip('B')
# dist = dist.strip('C')
# dist = dist.strip('D')
# dist = dist.strip('E')
# dist = dist.strip('F')
# dist = dist.strip('G')
# dist = dist.strip('H')
# dist = dist.strip('I')
# dist = dist.strip('J')
# dist = dist.strip('K')
# dist = dist.strip('L')
# dist = dist.strip('M')
# dist = dist.strip('N')
# dist = dist.strip('Ñ')
# dist = dist.strip('O')
# dist = dist.strip('P')
# dist = dist.strip('Q')
# dist = dist.strip('R')
# dist = dist.rstrip('S')
# dist = dist.strip('T')
# dist = dist.strip('U')
# dist = dist.strip('V')
# dist = dist.strip('W')
# dist = dist.strip('X')
# dist = dist.strip('Y')
# dist = dist.strip('Z')
# print(dist)

